openapi: 3.0.0
info:
  title: EU Transit Declaration Generator API
  description: This is a simple message generator for the European project NCTS (New Computerized Transit System) Phase 5.
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: https://ncts5.monnier.cloud
tags:
- name : messages
  description: transit messages sent by traders from the External Domain

paths:
  /example_xml:
    get:
      tags:
      - messages
      summary: Retrieve a static example XML message
      parameters:
        - name: messageType
          in: query
          required: true
          schema:
            type: string
            example: "CC014C"
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                type: string
  
  /dynamic_xml:
    get:
      tags:
      - messages
      summary: Retrieve a dynamic XML message
      parameters:
        - name: messageType
          in: query
          required: true
          schema:
            type: string
            example: "CC014C"
        - name: MRN
          in: query
          required: true
        - name: holderRIN
          in: query
          required: true
        - name: OoDep
          in: query
          required: true
        - name: holderEORI
          in: query
          required: true
          
      responses:
        "200":
          description: Successful response
          content:
            application/xml:
              schema:
                type: string
  
  
